spring:
  application:
    name: comparer
  datasource:
    url: jdbc:oracle:thin:@10.50.50.239:1521:devstage
    username: ibs
    password: ibs
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health,info